/* tslint:disable */
/* eslint-disable */
/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceLocation
 */
export interface PlaceLocation {
    /**
     * 
     * @type {number}
     * @memberof PlaceLocation
     */
    lat?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaceLocation
     */
    lng?: number;
}

/**
 * Check if a given object implements the PlaceLocation interface.
 */
export function instanceOfPlaceLocation(value: object): value is PlaceLocation {
    return true;
}

export function PlaceLocationFromJSON(json: any): PlaceLocation {
    return PlaceLocationFromJSONTyped(json, false);
}

export function PlaceLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lng': json['lng'] == null ? undefined : json['lng'],
    };
}

export function PlaceLocationToJSON(value?: PlaceLocation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lat': value['lat'],
        'lng': value['lng'],
    };
}

