/* tslint:disable */
/* eslint-disable */
/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Place } from './Place';
import {
    PlaceFromJSON,
    PlaceFromJSONTyped,
    PlaceToJSON,
} from './Place';

/**
 * 
 * @export
 * @interface PlacesResponseDTO
 */
export interface PlacesResponseDTO {
    /**
     * 
     * @type {Array<Place>}
     * @memberof PlacesResponseDTO
     */
    places?: Array<Place> | null;
    /**
     * 
     * @type {number}
     * @memberof PlacesResponseDTO
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof PlacesResponseDTO
     */
    totalPages?: number;
}

/**
 * Check if a given object implements the PlacesResponseDTO interface.
 */
export function instanceOfPlacesResponseDTO(value: object): value is PlacesResponseDTO {
    return true;
}

export function PlacesResponseDTOFromJSON(json: any): PlacesResponseDTO {
    return PlacesResponseDTOFromJSONTyped(json, false);
}

export function PlacesResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlacesResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'places': json['places'] == null ? undefined : ((json['places'] as Array<any>).map(PlaceFromJSON)),
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
    };
}

export function PlacesResponseDTOToJSON(value?: PlacesResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'places': value['places'] == null ? undefined : ((value['places'] as Array<any>).map(PlaceToJSON)),
        'currentPage': value['currentPage'],
        'totalPages': value['totalPages'],
    };
}

