/* tslint:disable */
/* eslint-disable */
/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceUrlDTO
 */
export interface PlaceUrlDTO {
    /**
     * 
     * @type {string}
     * @memberof PlaceUrlDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceUrlDTO
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceUrlDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PlaceUrlDTO
     */
    lat?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PlaceUrlDTO
     */
    lng?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceUrlDTO
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceUrlDTO
     */
    creator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PlaceUrlDTO
     */
    imageUrl?: string | null;
}

/**
 * Check if a given object implements the PlaceUrlDTO interface.
 */
export function instanceOfPlaceUrlDTO(value: object): value is PlaceUrlDTO {
    return true;
}

export function PlaceUrlDTOFromJSON(json: any): PlaceUrlDTO {
    return PlaceUrlDTOFromJSONTyped(json, false);
}

export function PlaceUrlDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceUrlDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lng': json['lng'] == null ? undefined : json['lng'],
        'address': json['address'] == null ? undefined : json['address'],
        'creator': json['creator'] == null ? undefined : json['creator'],
        'imageUrl': json['imageUrl'] == null ? undefined : json['imageUrl'],
    };
}

export function PlaceUrlDTOToJSON(value?: PlaceUrlDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'lat': value['lat'],
        'lng': value['lng'],
        'address': value['address'],
        'creator': value['creator'],
        'imageUrl': value['imageUrl'],
    };
}

