/* tslint:disable */
/* eslint-disable */
/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TwoFactorResponse
 */
export interface TwoFactorResponse {
    /**
     * 
     * @type {string}
     * @memberof TwoFactorResponse
     */
    sharedKey?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TwoFactorResponse
     */
    recoveryCodesLeft?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TwoFactorResponse
     */
    recoveryCodes?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof TwoFactorResponse
     */
    isTwoFactorEnabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TwoFactorResponse
     */
    isMachineRemembered?: boolean;
}

/**
 * Check if a given object implements the TwoFactorResponse interface.
 */
export function instanceOfTwoFactorResponse(value: object): value is TwoFactorResponse {
    return true;
}

export function TwoFactorResponseFromJSON(json: any): TwoFactorResponse {
    return TwoFactorResponseFromJSONTyped(json, false);
}

export function TwoFactorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TwoFactorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sharedKey': json['sharedKey'] == null ? undefined : json['sharedKey'],
        'recoveryCodesLeft': json['recoveryCodesLeft'] == null ? undefined : json['recoveryCodesLeft'],
        'recoveryCodes': json['recoveryCodes'] == null ? undefined : json['recoveryCodes'],
        'isTwoFactorEnabled': json['isTwoFactorEnabled'] == null ? undefined : json['isTwoFactorEnabled'],
        'isMachineRemembered': json['isMachineRemembered'] == null ? undefined : json['isMachineRemembered'],
    };
}

export function TwoFactorResponseToJSON(value?: TwoFactorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sharedKey': value['sharedKey'],
        'recoveryCodesLeft': value['recoveryCodesLeft'],
        'recoveryCodes': value['recoveryCodes'],
        'isTwoFactorEnabled': value['isTwoFactorEnabled'],
        'isMachineRemembered': value['isMachineRemembered'],
    };
}

