/* tslint:disable */
/* eslint-disable */
/**
 * WebApplication1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface UsersResponseDTO
 */
export interface UsersResponseDTO {
    /**
     * 
     * @type {Array<UserDTO>}
     * @memberof UsersResponseDTO
     */
    users?: Array<UserDTO> | null;
    /**
     * 
     * @type {number}
     * @memberof UsersResponseDTO
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof UsersResponseDTO
     */
    currentPage?: number;
}

/**
 * Check if a given object implements the UsersResponseDTO interface.
 */
export function instanceOfUsersResponseDTO(value: object): value is UsersResponseDTO {
    return true;
}

export function UsersResponseDTOFromJSON(json: any): UsersResponseDTO {
    return UsersResponseDTOFromJSONTyped(json, false);
}

export function UsersResponseDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersResponseDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserDTOFromJSON)),
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'currentPage': json['currentPage'] == null ? undefined : json['currentPage'],
    };
}

export function UsersResponseDTOToJSON(value?: UsersResponseDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserDTOToJSON)),
        'totalPages': value['totalPages'],
        'currentPage': value['currentPage'],
    };
}

