name: Trigger auto deployment for mkrolik-my-places

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mkrolik-my-places-AutoDeployTrigger-ae0a7cc5-5c2c-47a7-8d1b-4cdedb395956.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MKROLIKMYPLACES_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MKROLIKMYPLACES_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MKROLIKMYPLACES_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.MKROLIKMYPLACES_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MKROLIKMYPLACES_REGISTRY_PASSWORD }}
          containerAppName: mkrolik-my-places
          resourceGroup: DefaultResourceGroup-DEWC
          imageToBuild: mateuszkrolik/mkrolik-my-places:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


